#pragma once

#define MPP_RENDER_SORT_TEXTURE0_BITS_OFFSET		0
#define MPP_RENDER_SORT_TEXTURE0_BITS_SIZE			12

#define MPP_RENDER_SORT_TEXTURE1_BITS_OFFSET		(MPP_RENDER_SORT_TEXTURE0_BITS_OFFSET +  MPP_RENDER_SORT_TEXTURE0_BITS_SIZE)
#define MPP_RENDER_SORT_TEXTURE1_BITS_SIZE			12

#define MPP_RENDER_SORT_PROGRAM_BITS_OFFSET			(MPP_RENDER_SORT_TEXTURE1_BITS_OFFSET +  MPP_RENDER_SORT_TEXTURE1_BITS_SIZE)
#define MPP_RENDER_SORT_PROGRAM_BITS_SIZE			8

#define MPP_RENDER_SORT_DEPTH_BITS_OFFSET			(MPP_RENDER_SORT_PROGRAM_BITS_OFFSET +  MPP_RENDER_SORT_PROGRAM_BITS_SIZE)
#define MPP_RENDER_SORT_DEPTH_BITS_SIZE				24
