#include <filesystem>
#include <set>
#include <glm/geometric.hpp>
#include "mpp/SceneDocument.h"
using namespace std;
namespace mpp {
uint64_t scenePrimitiveTriangleCount(SceneModelDocument const& model){if(!model.visible)return 0;switch(model.source){case SceneModelSource::Box:return 12;case SceneModelSource::Sphere:{uint64_t triangles=20;for(uint32_t level=1;level<model.primitive.resolution;++level)triangles*=4;return triangles;}case SceneModelSource::Cylinder:return uint64_t(model.primitive.resolution)*4;case SceneModelSource::Grid:return uint64_t(model.primitive.segmentsX)*model.primitive.segmentsZ*2;default:return 0;}}
uint64_t SceneDocument::getKnownTriangleCount() const{uint64_t result=0;for(auto const& model:models)result+=scenePrimitiveTriangleCount(model);return result;}
size_t SceneDocument::getUnknownTriangleModelCount() const{size_t result=0;for(auto const& model:models)if(model.visible&&model.source==SceneModelSource::MppModel)++result;return result;}
DiagnosticBag SceneDocument::validate() const { DiagnosticBag d; if(version!=CurrentVersion)d.error("MPP-SCENE-001","Unsupported Scene version.",{sourcePath}); if(name.empty())d.error("MPP-SCENE-002","Scene name is required.",{sourcePath}); set<string> ids; for(auto const&m:models){if(m.id.empty()||!ids.insert(m.id).second)d.error("MPP-SCENE-003","Model IDs must be non-empty and unique.",{sourcePath},m.id); if(m.source==SceneModelSource::MppModel&&m.file.empty())d.error("MPP-SCENE-004","MPP model file is required.",{sourcePath},m.id);else if(m.source==SceneModelSource::MppModel){auto path=std::filesystem::path(m.file);if(path.is_absolute())d.warning("MPP-SCENE-009","Absolute model path is not portable.",{sourcePath},m.id);auto resolved=path.is_absolute()?path:std::filesystem::path(sourcePath).parent_path()/path;if(!std::filesystem::exists(resolved))d.error("MPP-SCENE-010","Model file does not exist: "+resolved.string(),{sourcePath},m.id);}if(m.source==SceneModelSource::Box&&(m.primitive.width<=0||m.primitive.height<=0||m.primitive.depth<=0))d.error("MPP-SCENE-015","Box dimensions must be positive.",{sourcePath},m.id);if(m.source==SceneModelSource::Sphere&&(m.primitive.radius<=0||m.primitive.resolution>8))d.error("MPP-SCENE-016","Sphere radius must be positive and subdivision resolution cannot exceed eight.",{sourcePath},m.id);if(m.source==SceneModelSource::Cylinder&&(m.primitive.height<=0||m.primitive.radius<0||m.primitive.topRadius<0||(m.primitive.radius==0&&m.primitive.topRadius==0)||m.primitive.resolution<3))d.error("MPP-SCENE-017","Cylinder length/radii/resolution are invalid.",{sourcePath},m.id);if(m.source==SceneModelSource::Grid&&(m.primitive.width<=0||m.primitive.depth<=0||m.primitive.segmentsX==0||m.primitive.segmentsZ==0))d.error("MPP-SCENE-018","Grid dimensions and segment counts must be positive.",{sourcePath},m.id);for(auto const&layer:m.layers)if(layer.empty())d.error("MPP-SCENE-011","Layer names cannot be empty.",{sourcePath},m.id); if(m.materialBinding.empty())d.warning("MPP-SCENE-005","Model has no logical material binding.",{sourcePath},m.id);} for(auto const&l:lights){if(l.id.empty()||!ids.insert(l.id).second)d.error("MPP-SCENE-006","Light IDs must be non-empty and unique.",{sourcePath},l.id);if(l.intensity<0||l.range<0)d.error("MPP-SCENE-012","Light intensity and range cannot be negative.",{sourcePath},l.id);if(l.type==SceneLightType::Directional&&glm::dot(l.direction,l.direction)<0.000001f)d.error("MPP-SCENE-013","Directional light direction cannot be zero.",{sourcePath},l.id);}if(lights.size()>8)d.error("MPP-SCENE-014","Scene exceeds the renderer limit of eight PBR lights.",{sourcePath},"lights"); if(camera.nearPlane<=0||camera.farPlane<=camera.nearPlane)d.error("MPP-SCENE-007","Camera clip distances are invalid.",{sourcePath},"camera"); if(environmentBinding.empty())d.warning("MPP-SCENE-008","Scene has no logical environment binding.",{sourcePath},"environment"); return d; } }
