#include <memory>
#include <sstream>
#include "utils/XmlReader.h"
#include "utils/StringUtils.h"
#include "mpp/resource-parsers/MppResourceParsersException.h"
#include "mpp/resource-parsers/SceneParser.h"
using namespace std;
namespace mpp::resource_parsers { namespace { glm::vec3 vec3(string const&s){istringstream i(s);glm::vec3 v;i>>v.x>>v.y>>v.z;return v;} bool boolean(string s){utils::StringUtils::toUpper(s);return s=="TRUE"||s=="1"||s=="YES";} SceneModelSource source(string s){utils::StringUtils::toUpper(s);if(s=="MPPMODEL")return SceneModelSource::MppModel;if(s=="BOX")return SceneModelSource::Box;if(s=="CYLINDER")return SceneModelSource::Cylinder;if(s=="GRID")return SceneModelSource::Grid;return SceneModelSource::Sphere;} }
SceneDocument SceneParser::fromFile(string const&filepath){unique_ptr<utils::XmlReader>r(utils::XmlReader::fromFile(filepath));auto data=r->readTree();if(data.getName()!="Scene")THROW_MPP_RESOURCE_PARSERS("Scene root must be Scene: "+filepath,__LINE__,__FILE__,__func__);SceneDocument d;d.sourcePath=filepath;d.version=data.hasEntry("version")?utils::StringUtils::parseUInt(data.getEntry("version").getValue()):1;d.name=data.hasEntry("name")?data.getEntry("name").getValue():"";if(data.hasEntry("environmentBinding"))d.environmentBinding=data.getEntry("environmentBinding").getValue();if(data.hasEntry("Camera")){auto const&c=data.getEntry("Camera");if(c.hasEntry("position"))d.camera.position=vec3(c.getEntry("position").getValue());if(c.hasEntry("target"))d.camera.target=vec3(c.getEntry("target").getValue());if(c.hasEntry("fov"))d.camera.fov=utils::StringUtils::parseFloat(c.getEntry("fov").getValue());if(c.hasEntry("near"))d.camera.nearPlane=utils::StringUtils::parseFloat(c.getEntry("near").getValue());if(c.hasEntry("far"))d.camera.farPlane=utils::StringUtils::parseFloat(c.getEntry("far").getValue());}if(data.hasEntry("Models"))for(auto const&e:data.getEntry("Models")){if(e.first!="Model")continue;auto const&m=e.second;SceneModelDocument x;x.id=m.getEntry("id").getValue();x.source=source(m.getEntry("source").getValue());if(m.hasEntry("file"))x.file=m.getEntry("file").getValue();if(m.hasEntry("translation"))x.translation=vec3(m.getEntry("translation").getValue());if(m.hasEntry("rotation"))x.rotationDegrees=vec3(m.getEntry("rotation").getValue());if(m.hasEntry("scale"))x.scale=vec3(m.getEntry("scale").getValue());if(m.hasEntry("materialBinding"))x.materialBinding=m.getEntry("materialBinding").getValue();if(m.hasEntry("visible"))x.visible=boolean(m.getEntry("visible").getValue());if(m.hasEntry("shadowCaster"))x.shadowCaster=boolean(m.getEntry("shadowCaster").getValue());if(m.hasEntry("Layers"))for(auto const&l:m.getEntry("Layers"))if(l.first=="Layer")x.layers.push_back(l.second.getValue());d.models.push_back(x);}if(data.hasEntry("Lights"))for(auto const&e:data.getEntry("Lights")){if(e.first!="Light")continue;auto const&l=e.second;SceneLightDocument x;x.id=l.getEntry("id").getValue();if(l.hasEntry("type")){auto t=l.getEntry("type").getValue();utils::StringUtils::toUpper(t);x.type=t=="POINT"?PbrLightType::Point:PbrLightType::Directional;}if(l.hasEntry("colour"))x.colour=vec3(l.getEntry("colour").getValue());if(l.hasEntry("intensity"))x.intensity=utils::StringUtils::parseFloat(l.getEntry("intensity").getValue());if(l.hasEntry("position"))x.position=vec3(l.getEntry("position").getValue());if(l.hasEntry("direction"))x.direction=vec3(l.getEntry("direction").getValue());if(l.hasEntry("range"))x.range=utils::StringUtils::parseFloat(l.getEntry("range").getValue());d.lights.push_back(x);}return d;}}
